# -*- coding: utf-8 -*-
"""aula001_agrupamento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xRD6Ly0PhHHayoYBe45oVndtJtyW-WAe
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

# DataSet
data = pd.read_csv("3.01. Country clusters.csv")

# Visualização dos Dados
plt.scatter(data["Longitude"], data["Latitude"])
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.xlim(-180, 180)
plt.ylim(-90, 90)
plt.show()

# Organização das Variáveis (dependente e independente)
x = data.iloc[:,1:3]
x

# Agrupamento Usando K-Means
kmeans = KMeans(3)
kmeans.fit(x)
clusters = kmeans.fit_predict(x)
clusters

# Organização do Resultado como DataFrame
data_clusters = data.copy()
data_clusters["Clusters"] = clusters
data_clusters

# Visualização do Resultado
plt.scatter(data_clusters["Longitude"], data_clusters["Latitude"], c=data_clusters["Clusters"], cmap="rainbow")
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.xlim(-180, 180)
plt.ylim(-90, 90)
plt.show()