# -*- coding: utf-8 -*-
"""aula002_regressaoLinearSimples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuyQCk2R5I2jfJs7nJYVOLEAJj30tC5K

**Regressão Linear Simples**
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Dados
data = pd.read_csv("1.01. Simple linear regression.csv")
data
#data.describe()

# Visualização dos Dados
y = data["GPA"]
x1 = data["SAT"]

# Plotagem dos Dados
plt.scatter(x1,y)
plt.xlabel("SAT", fontsize=20)
plt.ylabel("GPA", fontsize=20)
plt.show()

# Regressão Linear Simples (utilizando statsmodel)
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()

# Plotagem do Modelo de Regressão Linear Simples
plt.scatter(x1, y)
yhat = 0.0017*x1 + 0.275
fig = plt.plot(x1, yhat, lw=4, c="orange", label="Regressão Linear Simples")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("GPA", fontsize=20)
plt.show()