# -*- coding: utf-8 -*-
"""numeros-e-booleanos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QppsNl1WrebMcqT7E3aPuX7iaDnrT6Vn
"""

# NÚMEROS E VALORES BOOLEANOS
x1 = 5;
print(type(x1));

x2 = 4.75;
print(type(x2));

print(int(x2));
print(float(x1));

x3 = True;
print(type(x3));

x4 = False;
print(type(x4));