# -*- coding: utf-8 -*-
"""comentarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_gSb88omuFyF7qdcNSTrjmvasBM-9sGN
"""

# COMENTÁRIOS
# Comentário em uma única linha ...

"""
Comentário em múltiplas linhas ...
"""