# -*- coding: utf-8 -*-
"""aula004_preditores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brn3OGavb7S9m7blv9Ko0SCso2HX8VV3
"""

# Bibliotecas
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

# Dados
raw_data = pd.read_csv("2.02. Binary predictors.csv")
raw_data
data = raw_data.copy()
data["Admitted"] = data["Admitted"].map({"Yes":1, "No":0})
data["Gender"] = data["Gender"].map({"Female":1, "Male":0})
data

# Declaração das Variáveis Dependentes e Independentes
y = data["Admitted"]
x1 = data[["SAT","Gender"]]

# Regressão Logística
x = sm.add_constant(x1)
results = sm.Logit(y,x).fit()
results.summary()