# -*- coding: utf-8 -*-
"""aula009_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1blVmVFAm6gJldzap8Ax9Yg9gB98ts-1I
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans
from sklearn import preprocessing

# Dataset
raw_data = pd.read_csv("3.12. Example.csv")
#x_scaled = preprocessing.scale(raw_data)
x_scaled = raw_data.copy()

# Dendograma
sns.clustermap(x_scaled, cmap="mako")