# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQtA1q04bUp2pqwQutMBLSobzriEfjQq
"""

# ATRBUIÇÃO E COMPARAÇÃO
y = 5 ** 3;
print(y)
print(y == 125);
print(y == 126);