# -*- coding: utf-8 -*-
"""aula003_agrupamento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Spyo3jtIxv8lbIhLymazSiboYvBq9YD
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

# DataSet
data_raw = pd.read_csv("3.01. Country clusters.csv")
data = data_raw.copy()
data["Language"] = data["Language"].map({"English":0, "French":1, "German":2})

# Agrupamento Utilizando K-Means
x = data.iloc[:,1:4]
kmeans = KMeans(2)
kmeans.fit(x)
clusters = kmeans.fit_predict(x)

# Organização do DataSet Processado
processed_data = data.copy()
processed_data["Cluster"] = clusters
processed_data

# Visualização dos Dados
plt.scatter(processed_data["Longitude"], processed_data["Latitude"], c=processed_data["Cluster"], cmap="rainbow")
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.xlim(-180, 180)
plt.ylim(-90, 90)
plt.show()