# -*- coding: utf-8 -*-
"""aula002_tensores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d4WCUsDvGvxVq3oZ6CdA4oe6_gM3Kc29
"""

import numpy as np

m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m3 = np.array([[1, 2, 3], [4, 5, 6]])

t = np.array([m1, m2, m3])
t.shape