# -*- coding: utf-8 -*-
"""reatribuicao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEWmW17Qe0reHVaMFRC6otTx9KGlWBvZ
"""

# REATRIBUIÇÃO
z = 1;
print(z);
z = 10;
print(z);
print(z + 30);