# -*- coding: utf-8 -*-
"""aula007_segmentacaoEspecies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qz2Hvxg5mO-NFi7Pmjb63Xt-G31ICrWH
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

# Dataset
raw_data = pd.read_csv("iris-dataset.csv")
plt.scatter(raw_data["sepal_length"], raw_data["sepal_width"])
plt.xlabel("sepal length (cm)")
plt.ylabel("sepal width (cm)")
plt.show()

# Método do Cotovelo
x = raw_data.copy()

from sklearn import preprocessing
x_scaled = preprocessing.scale(x)

sqg = []
for k in range(1,21):
  kmeans = KMeans(k)
  kmeans.fit(x_scaled)
  sqg.append(kmeans.inertia_)

plt.plot(range(1,21), sqg)
plt.xlabel("Cluster [K]", fontsize=20)
plt.ylabel("SQG(K)", fontsize=20)
plt.show()

# Agrupamento Utilizando K-Means
kmeans = KMeans(3)
kmeans.fit(x_scaled)
clusters = kmeans.fit_predict(x_scaled)

processed_data = x.copy()
processed_data["Cluster"] = clusters
processed_data

plt.scatter(processed_data["sepal_length"], processed_data["sepal_width"], c=processed_data["Cluster"], cmap="rainbow")
plt.xlabel("sepal length (cm)", fontsize=20)
plt.ylabel("sepal width (cm)", fontsize=20)
plt.show()