# -*- coding: utf-8 -*-
"""aula002_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wnmIunpnEZzrtkJtw4_Ey1ANVsfPsqSr
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Dados
data = pd.read_csv("real_estate_price_size.csv")
data
#data.describe()

# Visualização dos Dados
y = data["price"]
x1 = data["size"]
plt.scatter(x1, y)
plt.xlabel("SIZE", fontsize=20)
plt.ylabel("PRICE", fontsize=20)
plt.show()

# Regressão Linear Simples (utilizando statsmodel)
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()

# Plotagem do Modelo de Regressão Linear Simples
plt.scatter(x1, y)
yhat = 223.1787 * x1 + 1.019e+05
fig = plt.plot(x1, yhat, lw=4, c="orange", label="Regressão Linear Simples")
plt.xlabel("SIZE")
plt.ylabel("PRICE")
plt.show()