# -*- coding: utf-8 -*-
"""aula003_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12NkIHj2Gb2IuSMJLie2WrfimZbiV46Do
"""

# Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

# Dados
data = pd.read_csv("real_estate_price_size_year.csv")
data

# Regressao Linear Simples
y = data["price"]
x1 = data["size"]
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()

# Regressão Linear Simples
x1 = data["year"]
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()

# Regressão Linear Múltipla
x1 = data[["size", "year"]]
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()