# -*- coding: utf-8 -*-
"""aula001_pacotesRelevantes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuEf439-PBn7vGOhTQ0QflLYco4KWTWO
"""

import numpy as np
import pandas as pd
import scipy
import statsmodels.api as sm
import matplotlib as plt
import seaborn as sns
import sklearn