# -*- coding: utf-8 -*-
"""aula004_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6Cy4eTXP3Mrm1CrcWJuHK-AniuhqVB1
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

# Dataset
data_raw = pd.read_csv("Categorical.csv")
data = data_raw.copy()
#data = data.drop(["Unnamed: 0"], axis=1)
data['continent'] = data['continent'].map({'North America':0,'Europe':1,'Asia':2,'Africa':3,'South America':4, 'Oceania':5,'Seven seas (open ocean)':6, 'Antarctica':7})
plt.scatter(data["Longitude"], data["Latitude"])
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.show()

# Agrupamento com K-Means
data
x = data.iloc[:,3:4]
kmeans = KMeans(7)
kmeans.fit(x)
clusters = kmeans.fit_predict(x)
processed_data = data.copy()
processed_data["Clusters"] = clusters

# Visualização do Agrupamento
plt.scatter(processed_data["Longitude"], processed_data["Latitude"], c=processed_data["Clusters"], cmap="rainbow")
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.show()