# -*- coding: utf-8 -*-
"""aula003_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oeLH60BLJcK8Es6UopERTqnKJOgkiKMm
"""

# Bibliotecas
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# Conjunto de Treinamento
observations = 50
x = np.random.uniform(1, 5, size=(observations,1))
delta_noise = 0.1
noise = np.random.uniform(-delta_noise, delta_noise, size=(observations,1))
target = 0.5*x + 0.7 + noise

plt.scatter(x, target)
plt.xlabel("x", fontsize=20)
plt.ylabel("y", fontsize=20)
plt.show()

# Treinamento Usando Gradiente Descendente
n = 0.001
w = 0
b = 0

for k in range(5000):
  sumW = 0
  sumB = 0
  for i in range(0, len(target)):
    sumW = sumW + (target[i] - b - w*x[i]) * x[i]
    sumB = sumB + (target[i] - b - w*x[i])
  w = w - n * (-2) * sumW
  b = b - n * (-2) * sumB

print(w, b)

# Plotagem do Modelo
plt.scatter(x, target)
plt.plot(x, w*x+b, color="red")
plt.xlabel("x", fontsize=20)
plt.ylabel("y", fontsize=20)
plt.show()