# -*- coding: utf-8 -*-
"""aula005_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvWgnCElpTik0dwzmekgsf34_EgyZyiw
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

# Dataset
raw_data = pd.read_csv("Countries-exercise.csv")
data = raw_data.copy()
plt.scatter(data["Longitude"], data["Latitude"])
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.xlim(-180, 180)
plt.ylim(-90, 90)
plt.show()

# Análise Pelo Método do Cotovelo
nc = 11;
x = data.iloc[:, 1:3]
sqg = []
for i in range(1,nc):
  kmeans = KMeans(i)
  kmeans.fit(x)
  sqg.append(kmeans.inertia_)

plt.plot(range(1,nc), sqg)
plt.xlabel("Cluster [K]", fontsize=20)
plt.ylabel("SQG(K)", fontsize=20)
plt.show()

# Agrupamento Utilizando K-Means
kmeans = KMeans(6)
kmeans.fit(x)
clusters = kmeans.fit_predict(x)
clusters
processed_data = data.copy()
processed_data["Cluster"] = clusters

# Visualização do Agrupamento
plt.scatter(processed_data["Longitude"], processed_data["Latitude"], c=processed_data["Cluster"], cmap="rainbow")
plt.xlim(-180, 180)
plt.ylim(-90, 90)
plt.xlabel("Longitude", fontsize=20)
plt.ylabel("Latitude", fontsize=20)
plt.show()