# -*- coding: utf-8 -*-
"""variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_9weF10ETd0sApWmajjBCLrXTZtjYb-
"""

# VARIÁVEIS
x = 5;
print(x);

y = 8;
print(y)

x, y = (1, 2);
print(x);
print(y);