# -*- coding: utf-8 -*-
"""aula008_dendograma_mapaCalor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NOJzsWVJBT5OVgQY2pECAkCcVs-ypLGQ
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans
from sklearn import preprocessing

# Dataset
raw_data = pd.read_csv("Country clusters standardized.csv", index_col="Country")
raw_data

x_scaled = raw_data.copy()
x_scaled = x_scaled.drop(["Language"], axis=1)
x_scaled

# Visualização do Dendograma
sns.clustermap(x_scaled, cmap="mako")