# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17UuDhz6BBGQJJjWCXT9yAnAdxx_KM2GW
"""

# ELEMENTOS DE INDEXAÇÃO
mensagem = "Olá!";
print(mensagem[0]);
print(mensagem[1]);
print(mensagem[2]);
print(mensagem[3]);