# -*- coding: utf-8 -*-
"""aula003_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwK5AtQaAY644Pevu0SQq1PosaboKOZS
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

# Dados
raw_data = pd.read_csv("Example-bank-data.csv")
raw_data
data = raw_data.copy()
data = data.drop(["Unnamed: 0"], axis = 1)
data["y"] = data["y"].map({"yes":1, "no":0})
data

# Visualização dos Dados
y = data["y"]
x1 = data["duration"]
plt.scatter(x1,y)
plt.xlabel("Duration", fontsize=20)
plt.ylabel("Y", fontsize=20)
plt.show()

# Regressão Logística
x = sm.add_constant(x1)
results = sm.Logit(y,x).fit()
results.summary()

def f(x,b0,b1):
  return np.array(np.exp(b0 + b1*x) / (1 + np.exp(b0 + b1*x)))

f_sorted = np.sort(f(x1,results.params[0],results.params[1]))
x_sorted = np.sort(np.array(x1))

plt.scatter(x1,y, color="C0")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("Admitted", fontsize=20)
plt.plot(x_sorted, f_sorted, color="C8")
plt.show()

results.summary()