# -*- coding: utf-8 -*-
"""regressaoLinear_dadosCategoricos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pH__CKrmvEzzGZX5pcOXo9Eo0hjh63i2
"""

# Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

# Dados
raw_data = pd.read_csv("1.03. Dummies.csv")
raw_data

# Corrigindo a Variável Categórica
data = raw_data.copy()
data["Attendance"] = data["Attendance"].map({"Yes":1, "No":0})
data

# Regressão Linear Múltipla
y = data["GPA"]
x1 = data[["SAT", "Attendance"]]
x = sm.add_constant(x1)
results = sm.OLS(y, x).fit()
results.summary()

# Visualização dos Dados
plt.scatter(data["SAT"], y, c=data["Attendance"], cmap="RdYlGn_r")
yhat_no = 0.6439 + 0.0014*data["SAT"]
yhat_yes = 0.8665 + 0.0014*data["SAT"]
yhat = 0.0017*data["SAT"] + 0.275
fig = plt.plot(data["SAT"], yhat_no, lw=2, c="#006837")
fig = plt.plot(data["SAT"], yhat_yes, lw=2, c="#a50026")
fig = plt.plot(data["SAT"], yhat, lw=3, c="#4C72B0", label="Regressão Linear Simples")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("GPA", fontsize=20)
plt.show()

# Predição com a Regressão Linear
x
new_data = pd.DataFrame({"const":1, "SAT":[1700, 1670], "Attendance":[0,1]})
new_data = new_data[["const", "SAT", "Attendance"]]
new_data
new_data.rename(index={0:"Bob", 1:"Alice"})
predictions = results.predict(new_data)
predictions
predictionsdf = pd.DataFrame({"Predictions":predictions})
joined = new_data.join(predictionsdf)
joined.rename(index={0:"Bob", 1:"Alice"})