# -*- coding: utf-8 -*-
"""regressaoLinear-fechamento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Skg0pVEP4CttdnpTOSBv44jGA3pOMfAC
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

# Dados
data = pd.read_csv("FuelConsumptionCo2.csv")
#data
#data.describe()
y = data["CO2EMISSIONS"]
x1 = data["FUELCONSUMPTION_CITY"]
plt.scatter(x1,y)
plt.xlabel("FUEL CONSUMPTION")
plt.ylabel("CO2 EMISSIONS")
plt.show()

# Regressão Linear Simples
x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()
results.summary()

# Plotagem da Regressão Linear Simples
plt.scatter(x1,y)
yhat = 13.8764*x1 + 71.7202
fig = plt.plot(x1, yhat, lw=3, c="red", label="Regressão Linear Simples")
plt.xlabel("FUEL CONSUMPTION")
plt.ylabel("CO2 EMISSIONS")
plt.show()

# Predição
x
new_data = pd.DataFrame({"const":[1], "FUELCONSUMPTION_CITY":[15]})
new_data = new_data[["const", "FUELCONSUMPTION_CITY"]]
new_data
predictions = results.predict(new_data)
predictions
predictionsdf = pd.DataFrame({"Predictions":predictions})
joined = new_data.join(predictionsdf)
joined