# -*- coding: utf-8 -*-
"""aula001_regressaoLogistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I9PkifKho5EY7b9w51L-Yfff1zHGPTMe
"""

# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

# Dados
raw_data = pd.read_csv("2.01. Admittance.csv")
raw_data
# Inserindo Dummies
data = raw_data.copy()
data["Admitted"] = data["Admitted"].map({"Yes":1, "No":0})
data

# Visualização dos Dados
y = data["Admitted"]
x1 = data["SAT"]
plt.scatter(x1,y)
plt.xlabel("SAT", fontsize=20)
plt.ylabel("Admitted", fontsize=20)
plt.show()

# Regressão Linear Simples
x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()
results.summary()

#yhat = 0.0022*x1 - 3.2519
yhat = results.params[0] + results.params[1]*x1

plt.scatter(x1,y, color="C0")
fig = plt.plot(x1, yhat, lw=3, color="C8")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("Admitted", fontsize=20)
plt.show()

# Regressão Logística
results = sm.Logit(y,x).fit()

def f(x,b0,b1):
  return np.array(np.exp(b0 + b1*x) / (1 + np.exp(b0 + b1*x)))

f_sorted = np.sort(f(x1,results.params[0],results.params[1]))
x_sorted = np.sort(np.array(x1))

plt.scatter(x1,y, color="C0")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("Admitted", fontsize=20)
plt.plot(x_sorted, f_sorted, color="C8")
plt.show()