# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152JTKxKhnB_aeg97DWV4avxJq65NhFzA
"""

# STRINGS
nome = "George";
print(nome);
print(type(nome));

y = 10;
print(f'Você tem {y} reais na carteira.');