# -*- coding: utf-8 -*-
"""operadores-aritmeticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7FCJcduv6xoPqEqfHmxr6af58n82ESs
"""

# OPERADORES ARITMETICOS
print(1 + 3);
print(2 - 2);
print(10 * 2);
print(10 / 2);
print(16 / 3);
print(10 % 3);
print(5 ** 3);